// react/src/navigation/Navigation.tsx
import { Link } from 'react-router-dom';

import { PATH } from '../utilities/constants';
import './navigation.css'

function Navigation() {
    return (
        <nav>
            <ul>
                <li>
                    <Link to={PATH.MAIN}>Start</Link>
                </li>
                <li>
                    <Link to={PATH.TRANSACTIONS}>Transactions</Link>
                </li>
            </ul>
        </nav>
    );
}

export default Navigation;

// qwik/src/components/navigation/Navigation.tsx

import { component$, useStylesScoped$ } from '@builder.io/qwik';

import { PATH } from '../../utilities/constants';
import styles from "./navigation.css?inline";

const Navigation = component$(() => {
    useStylesScoped$(styles);

    return (
        <nav>
            <ul>
                <li>
                    <a href={PATH.MAIN}>Start</a>
                </li>
                <li>
                    <a href={PATH.TRANSACTIONS}>Transactions</a>
                </li>
            </ul>
        </nav>
    );
}
);


export default Navigation;
