// react/src/transactions-list/TransactionsList.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import { TransactionListData } from '../utilities/types';
import { API_PATH } from '../utilities/constants';
import { DisplayTransactionState } from '../partials'
import './transactions-list.css';

function TransactionsList(): React.ReactElement {
    const initialData: TransactionListData = {
        startFromTransactionIndex: 0,
        totalTransactionsCount: 0,
        numberOfTransactionsPerPage: 5,
        listOfTransactions: []
    }

    const [error, setError] = React.useState('');
    const [isLoaded, setIsLoaded] = React.useState(false);
    const [data, setData] = React.useState(initialData);

    const {
        startFromTransactionIndex,
        totalTransactionsCount,
        numberOfTransactionsPerPage,
        listOfTransactions
    } = data;


    function goToPage(targetPageIndex: number): void {
        // Clamp it
        refreshTheTable(Math.min(Math.max(targetPageIndex, 0), totalTransactionsCount));
    }

    function refreshTheTable(startFromTransactionIndex: number = 0): void {
        fetch(API_PATH.TRANSACTIONS + '?startFromTransactionIndex=' + startFromTransactionIndex)
            .then(res => res.json())
            .then(
                (result) => {
                    setIsLoaded(true);
                    setData(result);
                },
                (error) => {
                    setIsLoaded(true);
                    setError(error.message);
                }
            )
    }

    React.useEffect(
        () => {
            refreshTheTable()
        }, []
    );

    if (error) {
        return <div>Error: {error}</div>;
    }

    if (!isLoaded) {
        return <div>Loading...</div>;
    }

    if (listOfTransactions?.length > 0) {
        return (
            <div>
                <table>
                    <thead>
                        <tr>
                            <td>Transaction ID</td>
                            <td>State</td>
                            <td className='col-aligned-right'>Amount</td>
                        </tr>
                    </thead>
                    <tbody>
                        {listOfTransactions.map(transaction => (
                            <tr key={transaction.id}>
                                <td><Link to={transaction.id}>{transaction.id}</Link></td>
                                <td><DisplayTransactionState state={transaction.state} /></td>
                                <td className='col-aligned-right'>{transaction.amount} &euro;</td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                <ul id="controls">
                    <li id="page-counter">{totalTransactionsCount} transactions</li>
                    <li><button onClick={() => goToPage(0)}>|&lt;</button></li>
                    <li><button onClick={() => goToPage(startFromTransactionIndex - numberOfTransactionsPerPage)}>&lt;</button></li>
                    <li><button onClick={() => goToPage(startFromTransactionIndex + numberOfTransactionsPerPage)}>&gt;</button></li>
                    <li><button onClick={() => goToPage(totalTransactionsCount - numberOfTransactionsPerPage)}>&gt;|</button></li>
                </ul>
            </div >
        );
    } else {
        return <div>No transactions were found</div>;
    }
}

export default TransactionsList;

// angular/src/app/transactions-list/transactions-list.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { RouterLink } from '@angular/router';

import { PATH, API_PATH } from '../utilities/constants';
import { NgForOf } from '@angular/common';
import { DisplayTransactionStateComponent } from '../display-transaction-state/display-transaction-state.component';
import { Transaction } from '../utilities/types';

@Component({
  selector: 'app-transactions-list',
  standalone: true,
  imports: [NgForOf, DisplayTransactionStateComponent, RouterLink],
  templateUrl: './transactions-list.component.html',
  styleUrl: './transactions-list.component.css'
})
export class TransactionsListComponent {
  path = PATH

  startFromTransactionIndex = 0;
  totalTransactionsCount = 0;
  numberOfTransactionsPerPage = 0;
  listOfTransactions: Transaction[] = [];

  isLoaded = false;
  error = '';

  constructor(private http: HttpClient) { }

  refreshTheTable(startFromTransactionIndex: number = 0): void {
    this.http.get<any>(API_PATH.TRANSACTIONS + '?startFromTransactionIndex=' + startFromTransactionIndex).subscribe(result => {
      this.isLoaded = true;
      this.listOfTransactions = result.listOfTransactions
      this.error = '';
    });
  }

  goToPage(targetPageIndex: number): void {
    // Clamp it
    this.refreshTheTable(Math.min(Math.max(targetPageIndex, 0), this.totalTransactionsCount));
  }

  ngOnInit() {
    this.refreshTheTable(0);
  }
}

<table>
    <thead>
        <tr>
            <td>Transaction ID</td>
            <td>State</td>
            <td className='col-aligned-right'>Amount</td>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let transaction of listOfTransactions">
            <td><a [routerLink]="[path.TRANSACTIONS, transaction.id]">{{transaction.id}}</a></td>
            <td><app-display-transaction-state state={{transaction.state}} /></td>
            <td className='col-aligned-right'>{{transaction.amount}} &euro;</td>
        </tr>
    </tbody>
</table>
