// qwik/src/components/partials/DisplayTransactionState.tsx
import { component$ } from '@builder.io/qwik';

import { TransactionState } from '../../utilities/types';
import translations from '../../utilities/translations';
import type DisplayTransactionStateProps from './types';

const DisplayTransactionState = component$(({ state }: DisplayTransactionStateProps) => {
    if (state) {
        // TODO: An error might be lurking here, if the state is not mappeable
        return (
            <span>{translations.transactionState[state]}</span>
        );
    }

    return (<span>{translations.transactionState[TransactionState.Unknown]}</span>);
});

export default DisplayTransactionState;

// svelte/src/lib/partials/DisplayTransactionState.svelte
<script lang="ts">
    import { TransactionState } from '../utilities/types';
    import translations from '../utilities/translations';

    export let state;
    
    let stateText = translations.transactionState[TransactionState.Unknown];

    if (state) {
        // TODO: FIXME: Fix TS error
        stateText = translations.transactionState[state];
    }
</script>

<span>{stateText}</span>
