// angular/src/app/transaction-details/transaction-details.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';

import { API_PATH, PATH } from '../utilities/constants';
import { TransactionDetail } from '../utilities/types';
import { DisplayTransactionStateComponent } from '../display-transaction-state/display-transaction-state.component';

@Component({
  selector: 'app-transaction-details',
  standalone: true,
  imports: [RouterLink, DisplayTransactionStateComponent],
  templateUrl: './transaction-details.component.html',
  styleUrl: './transaction-details.component.css'
})
export class TransactionDetailsComponent {
  path = PATH;

  id: string | null = "";

  data: TransactionDetail = {
    id: '',
    state: 0,
    amount: 0,
    dateUnix: 0,
    cardHolder: '',
    notes: ''
  }
  
  constructor(
    private route: ActivatedRoute,
    private http: HttpClient,
    private router: Router
  ) {}
  
  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id');
    
    if (this.id) {
      this.http.get<any>(API_PATH.TRANSACTION_DETAILS + '/' + this.id).subscribe(result => {
        // console.log('transaction-details.component.ts #34 > result', result);
        this.data = result
      });
    } else {
      this.router.navigate([PATH.TRANSACTIONS]);
    }
  }
}

<div>
    <a routerLink={{path.TRANSACTIONS}}>
        Back
    </a>

    <h2>Transaction: {{data.id}}</h2>

    <section id="details">
        <div className='details-field'>State:</div>
        <div className='details-value'><app-display-transaction-state state={{data.state} /></div>

        <div className='details-field'>Amount:</div>
        <div className='details-value'>{{data.amount}} &euro;</div>

        <div className='details-field'>Date:</div>
        <div className='details-value'>{{data.dateUnix}}</div>

        <div className='details-field'>Card holder:</div>
        <div className='details-value'>{{data.cardHolder}}</div>

        <div className='details-field'>Notes:</div>
        <div className='details-value'>{{data.notes}}</div>
    </section>
</div>

// react/src/transaction-details/TransactionDetails.tsx
import React from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';

import { PATH, API_PATH } from '../utilities/constants';
import { TransactionDetail } from '../utilities/types';
import { DisplayTransactionState } from '../partials';
import './transaction-details.css';

function TransactionsDetails() {
    const initialData: TransactionDetail = {
        id: '',
        state: 0,
        amount: 0,
        dateUnix: 0,
        cardHolder: '',
        notes: ''
    };

    const [error, setError] = React.useState('');
    const [isLoaded, setIsLoaded] = React.useState(false);
    const [data, setData] = React.useState(initialData);

    let navigate = useNavigate();

    let urlParams = useParams();

    React.useEffect(
        () => {
            if (!urlParams?.transactionId) {
                navigate(PATH.TRANSACTIONS)
            }

            fetch(API_PATH.TRANSACTION_DETAILS + '/' + urlParams?.transactionId)
                .then(res => res.json())
                .then(
                    (result) => {
                        setIsLoaded(true);
                        setData(result);
                    },
                    (error) => {
                        setIsLoaded(true);
                        setError(error.message);
                    }
                )
        }, []
    );

    if (error) {
        return <div>Error: {error}</div>;
    } else if (!isLoaded) {
        return <div>Loading...</div>;
    } else {
        if (data) {
            return (
                <div>
                    <Link to={PATH.TRANSACTIONS}>
                        Back
                    </Link>

                    <h2>Transaction: {data.id}</h2>
                    
                    <section id="details">
                        <div className='details-field'>State:</div>
                        <div className='details-value'><DisplayTransactionState state={data.state} /></div>

                        <div className='details-field'>Amount:</div>
                        <div className='details-value'>{data.amount} &euro;</div>

                        <div className='details-field'>Date:</div>
                        <div className='details-value'>{data.dateUnix}</div>

                        <div className='details-field'>Card holder:</div>
                        <div className='details-value'>{data.cardHolder}</div>

                        <div className='details-field'>Notes:</div>
                        <div className='details-value'>{data.notes}</div>
                    </section>
                </div>
            );
        }

        return (
            <div>Transaction data couldn't be found</div>
        );
    }
}

export default TransactionsDetails;
