// react/src/navigation/Navigation.tsx
import { Link } from 'react-router-dom';

import { PATH } from '../utilities/constants';
import './navigation.css'

function Navigation() {
    return (
        <nav>
            <ul>
                <li>
                    <Link to={PATH.MAIN}>Start</Link>
                </li>
                <li>
                    <Link to={PATH.TRANSACTIONS}>Transactions</Link>
                </li>
            </ul>
        </nav>
    );
}

export default Navigation;

// angular/src/app/navigation/navigation.component.ts
import { Component } from '@angular/core';

import { PATH } from '../utilities/constants';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './navigation.component.html',
  styleUrl: './navigation.component.css'
})

export class NavigationComponent {
  path = PATH
}

<nav>
    <ul>
        <li>
            <a routerLink={{path.MAIN}}>Start</a>
        </li>
        <li>
            <a routerLink={{path.TRANSACTIONS}}>Transactions</a>
        </li>
    </ul>
</nav>
